Handle empty repositories
scm-manager/argo-cd pull request #3
Opened 2024-11-12 15:04 UTC by pfeuffer

2024-11-14 11:08 UTC, zT-1337 requested changes

2024-11-14 11:08 UTC, zT-1337 commented on go.mod
> +replace github.com/scm-manager/goscm => /home/rene/development/cloudogu/goscm
Reminder to remove this "replace"

2024-11-14 11:08 UTC, zT-1337 commented on applicationset/services/scm_provider/scm-manager_test.go
> +func scmManagerMockHandler(t *testing.T, emptyRepo bool) func(http.ResponseWriter, *http.Request) {
Not a huge fan of the boolean argument and the switch case inside this MockHandler. I would prefer to have as little logic as possible within mocks and rather seperate it into different mock functions.

2024-11-15 07:39 UTC, pfeuffer commented on applicationset/services/scm_provider/scm-manager_test.go
> +func scmManagerMockHandler(t *testing.T, emptyRepo bool) func(http.ResponseWriter, *http.Request) {
I can feel that. I've tried to make this better, but had no good idea. Maybe you can take another look...

2024-11-15 12:27 UTC, zT-1337 commented on applicationset/services/scm_provider/scm-manager_test.go
> +func scmManagerMockHandler(t *testing.T, emptyRepo bool) func(http.ResponseWriter, *http.Request) {
That is already an improvement. I would be fine merging this. But I will try to come up with an idea until monday.

2024-11-18 12:49 UTC, merged